export const playerData = [
  {
      name: "Yvonne Barrasso",
      rank: 34,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 32,
      active: true,
      nameFirst: "Yvonne",
      nameLast: "Barrasso"
    },
    {
      name: "Chuck Beavers",
      rank: 89,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 89,
      active: true,
      nameFirst: "Chuck",
      nameLast: "Beavers"
    },
    {
      name: "Mike Bowles",
      rank: 58,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 57,
      active: true,
      nameFirst: "Mike",
      nameLast: "Bowles"
    },
    {
      name: "Kiall Caudle",
      rank: 76,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 75,
      active: true,
      nameFirst: "Kiall",
      nameLast: "Caudle"
    },
    {
      name: "Jimmy Kempf Sr",
      rank: 50,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 52,
      active: true,
      nameFirst: "Jimmy",
      nameLast: "Kempf Sr"
    },
    {
      name: "Jimmy Kempf Jr",
      rank: 40,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 40,
      active: false,
      nameFirst: "Jimmy",
      nameLast: "Kempf Jr"
    },
    {
      name: "Johnny Kempf III",
      rank: 51,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 51,
      active: false,
      nameFirst: "Johnny",
      nameLast: "Kempf III"
    },
    {
      name: "Nick Ruslander",
      rank: 38,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 38,
      active: true,
      nameFirst: "Nick",
      nameLast: "Ruslander"
    },
    {
      name: "Justin Kelly",
      rank: 47,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 47,
      active: false,
      nameFirst: "Justin",
      nameLast: "Kelly"
    },
    {
      name: "Brian Bailey",
      rank: 96,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 93,
      active: true,
      nameFirst: "Brian",
      nameLast: "Bailey"
    },
    {
      name: "Will Bailey",
      rank: 84,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 77,
      active: true,
      nameFirst: "Will",
      nameLast: "Bailey"
    },
    {
      name: "Bill Malatesta",
      rank: 76,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 75,
      active: false,
      nameFirst: "Bill",
      nameLast: "Malatesta"
    },
    {
      name: "John Fratantuono",
      rank: 41,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 41,
      active: true,
      nameFirst: "John",
      nameLast: "Fratantuono"
    },
    {
      name: "John Baker",
      rank: 67,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 70,
      active: true,
      nameFirst: "John",
      nameLast: "Baker"
    },
    {
      name: "Peggy Rollins",
      rank: 31,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 32,
      active: true,
      nameFirst: "Peggy",
      nameLast: "Rollins"
    },
    {
      name: "Kim DeAngelis",
      rank: 44,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 46,
      active: true,
      nameFirst: "Kim",
      nameLast: "DeAngelis"
    },
    {
      name: "Maria Eyler",
      rank: 39,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 44,
      active: true,
      nameFirst: "Maria",
      nameLast: "Eyler"
    },
    {
      name: "Deena Resumadero",
      rank: 58,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 53,
      active: true,
      nameFirst: "Deena",
      nameLast: "Resumadero"
    },
    {
      name: "Jessica Rousch",
      rank: 35,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 30,
      active: true,
      nameFirst: "Jessica",
      nameLast: "Rousch"
    },
    {
      name: "Robin Morgan",
      rank: 37,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 42,
      active: true,
      nameFirst: "Robin",
      nameLast: "Morgan"
    },
    {
      name: "Caitlin Haskett",
      rank: 32,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 33,
      active: true,
      nameFirst: "Caitlin",
      nameLast: "Haskett"
    },
    {
      name: "Nate Robinson",
      rank: 32,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 33,
      active: true,
      nameFirst: "Nate",
      nameLast: "Robinson"
    },
    {
      name: "Tim Allen",
      rank: 49,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 51,
      active: true,
      nameFirst: "Tim",
      nameLast: "Allen"
    },
    {
      name: "Chuck Rice",
      rank: 49,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 50,
      active: true,
      nameFirst: "Chuck",
      nameLast: "Rice"
    },
    {
      name: "Dawn Higgs",
      rank: 38,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 38,
      active: false,
      nameFirst: "Dawn",
      nameLast: "Higgs"
    },
    {
      name: "Alan Phelps",
      rank: 73,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 71,
      active: false,
      nameFirst: "Alan",
      nameLast: "Phelps"
    },
    {
      name: "Bob Kaczorowski",
      rank: 52,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 49,
      active: true,
      nameFirst: "Bob",
      nameLast: "Kaczorowski"
    },
    {
      name: "Ken Jackson",
      rank: 51,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 53,
      active: true,
      nameFirst: "Ken",
      nameLast: "Jackson"
    },
    {
      name: "Dan Hamilton",
      rank: 43,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 46,
      active: true,
      nameFirst: "Dan",
      nameLast: "Hamilton"
    },
    {
      name: "Josh Blaylock",
      rank: 64,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 64,
      active: true,
      nameFirst: "Josh",
      nameLast: "Blaylock"
    },
    {
      name: "James Taylor",
      rank: 58,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 61,
      active: true,
      nameFirst: "James",
      nameLast: "Taylor"
    },
    {
      name: "Randy Thomas",
      rank: 49,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 55,
      active: true,
      nameFirst: "Randy",
      nameLast: "Thomas"
    },
    {
      active: true,
      name: "Paul Rivas",
      rank: 72,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 72,
      nameFirst: "Paul",
      nameLast: "Rivas"
    },
    {
      name: "Eddy Ekstrom",
      rank: 52,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 52,
      active: true,
      nameFirst: "Eddy",
      nameLast: "Ekstrom"
    },
    {
      name: "Joe Malatesta",
      rank: 76,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 73,
      active: true,
      nameFirst: "Joe",
      nameLast: "Malatesta"
    },
    {
      name: "Mike DiZebba",
      rank: 50,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 49,
      active: true,
      nameFirst: "Mike",
      nameLast: "DiZebba"
    },
    {
      name: "Charlene Stout",
      rank: 48,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 42,
      active: true,
      nameFirst: "Charlene",
      nameLast: "Stout"
    },
    {
      name: "Crystal Bowie",
      rank: 52,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 53,
      active: false,
      nameFirst: "Crystal",
      nameLast: "Bowie"
    },
    {
      name: "Matthew Bowie",
      rank: 44,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 42,
      active: false,
      nameFirst: "Matthew",
      nameLast: "Bowie"
    },
    {
      name: "Steven Ford",
      rank: 72,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 72,
      active: false,
      nameFirst: "Steven",
      nameLast: "Ford"
    },
    {
      name: "Bill Shores Sr.",
      rank: 44,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 43,
      active: false,
      nameFirst: "Bill",
      nameLast: "Shores Sr"
    },
    {
      name: "Matt Doxie",
      rank: 56,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 56,
      active: false,
      nameFirst: "Matt",
      nameLast: "Doxie"
    },
    {
      name: "Gary Buchanan",
      rank: 50,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      seasonRankStart: 50,
      active: false,
      nameFirst: "Gary",
      nameLast: "Bushanan"
    },
    {
      name: "Nick Capuano",
      rank: 48,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      active: true,
      nameFirst: "Nick",
      nameLast: "Capuano"
    },
    {
      name: "Mike Trujillo",
      rank: 44,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      active: false,
      nameFirst: "Mike",
      nameLast: "Trujillo"
    },
    {
      name: "Barry Dunaway",
      rank: 73,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      active: true,
      nameFirst: "Barry",
      nameLast: "Dunaway"
    },
    {
      name: "Ann Pieper",
      rank: 50,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      active: true,
      nameFirst: "Ann",
      nameLast: "Pieper"
    },
    {
      name: "Loren Lutz",
      rank: 51,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      active: true,
      nameFirst: "Loren",
      nameLast: "Lutz"
    },
    {
      name: "Dean Catterton",
      rank: 68,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      active: true,
      nameFirst: "Dean",
      nameLast: "Catterton"
    },
    {
      name: "Jimmy Fratz",
      rank: 65,
      matchesPlayed: 0,
      matchWin: 0,
      matchLoss: 0,
      gamesWon: 0,
      gamesLoss: 0,
      active: true,
      nameFirst: "Jimmy",
      nameLast: "Fratz"
    }
]

